# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Crafting values in cancer care across the UK"
email: "info@valuesincancercare.uk"
description: "We help people suffering from cancer"
baseurl: "/"
url: "http://www.valuesincancercare.uk"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "Maria Ignacia Arteaga Perez and Clara Therond"
organizerAlternateName: "PhD students at UCL"
organizerDescription: "Two anthropologist who are passionate about cancer care"
organizerEmail: "info@valuesincancercare.uk"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.ucl.ac.uk/anthropology/people/research-students/maria-arteaga"

# Head
metaKeywords: "event, cancer, care, london, anthropology, medicine"
twitterAccount: "‎@UCLanthropology"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
bottomNavigationLinks:
 - {link: "https://www.eventbrite.co.uk/e/interdisciplinary-conference-crafting-values-in-cancer-care-across-the-uk-tickets-43053132077", text: "Register"}
rightNavigationButtons:
 - {link: "https://www.eventbrite.co.uk/e/interdisciplinary-conference-crafting-values-in-cancer-care-across-the-uk-tickets-43053132077", text: "Register"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Crafting values in cancer care <typeout>"
eventDate: "June 5th, 2018"
typeoutTextValues: '"", "across the UK", "call for papers open", "workshop", "conference", "round table", '
typeoutFallback: "across the UK"
heroButtons:
 - {link: "https://www.eventbrite.co.uk/e/interdisciplinary-conference-crafting-values-in-cancer-care-across-the-uk-tickets-43053132077", text: "Register"}
 - {permalink: "/blog/call-for-papers", text: "Call for papers"}

# About Block
aboutTitle: "About Cancer Care"
aboutBlock:
 - {title: "Workshop", image: "workshop.png", text: "Healthcare professionals working in the field of cancer care will be invited to reflect, along with panellists and the wider audience on ethnographic work carried out by post-fieldwork PhD students and academics in the UK." }
 - {title: "Round table", image: "roundtable.png", text: "Led by Dr Sahra Gibbon and three leading academics working in the field of cancer, to reflect on the continuum of cancer care, and possible lines for future research and collaboration between ethnography and oncology in the UK. Confirmed speakers are: Dr Sahra Gibbon (chair), Dr Anne Kerr and Dr Anne Lanceley." }
 - {title: "Keynotes", image: "key-note.png", text: "Professor Daniel Hochhauser (UCL Cancer Institute) and Professor Sophie Day (Goldmisths University) are two leading academics in the UK who will share with us their perspectives on the values and dynamics that shape cancer care in the country. Their presentations will be followed by Dr. Sahra Gibbon's closing remarks." }


# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 2
rockstarSpeakersTitle: "Keynote speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "University College London, Anthropology Department"
eventLocationLink: "http://www.ucl.ac.uk/anthropology/"
eventStreetAddress: "14 Taviton St"
eventAddressLocality: "London"
eventAddressLocalityRegion: "Greater London"
eventPostalCode: "WC1H 0BW"
eventAddressCountry: "United Kingdom"
eventStartTime: "2018-06-05T09:00"
eventDoorTime: "08:30"
eventEndTime: "2018-06-05T21:00"
eventPlaceCoordinates: "51.525163, -0.131572"
mapCenterCoordinates: "51.525163, -0.131572"
mapMobileCenterCoordinates: "51.525163, -0.131572"


# Partners Block
organizersTitle: "Organiser"
partnersTitle: "Sponsors"


# Footer
socialLinks:
 - {link: "https://twitter.com/UCLanthropology", icon: "twitter"}
 - {link: "https://facebook.com/UCLAnthropology", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.ucl.ac.uk/anthropology/", text: "UCL Anthropology"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:info@valuesincancercare.uk", text: "info@valuesincancercare.uk"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "devfestua"

# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "About us"
aboutUs: "We are two anthropologist who are passionate about cancer care."
